### PR TITLE
Update to latest syntax, replace source.ruby.rails

### PR DESCRIPTION
**Pull request by ypresto**
- Copied latest tmLanguage from slim-template/ruby-slim.tmbundle
- Replaced `source.ruby.rails` with `source.ruby` to fix ruby highlighting

### CODE REVIEW

**Comment by ypresto** [comment]
@sianglim
If you don't have enough time to release this, I'll fork this plugin :)
(I'm currently working hard with slim files, so I really wants this soon..! >_<)

**Comment by tdegrunt** [comment]
Will you publish your extension?

**Comment by ypresto** [comment]
@tdegrunt
I want to wait more for author's response.
This plugin already has near 3K users and perhaps most of they won't switch to new plugin.

**Comment by sianglim** [comment]
Hi @ypresto, thanks for taking the time submit a pull request.

I just saw the mention for your comment from 2 days ago (not sure why I didn't get emails for the earlier comments).

I'm really happy for you to fork this. I can also merge your PR and publish the updated extension (if I remember how 😄 ).

I tried to fix this several times but really had no idea how, so thanks again.


Cheers,
Siang

**Comment by sianglim** [comment]
Hi again @ypresto and @tdegrunt,

I've updated the extension in the Marketplace.


Siang

**Comment by ypresto** [comment]
Thanks! Confirmed syntax highlight is working after update!!

**Pull request merged**
